sudo: required
services:
  - docker
env: 
    global:
        - DOCKER_VERSION=1.10.1-0~trusty
        - DOCKER_COMPOSE_VERSION=1.6.0

before_install:

    # reinstall docker-compose at specific version
    - sudo apt install docker-compose
script:
    - docker version
